version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: lesson9-web
    depends_on:
      - app
    volumes:
      - ./:/var/www/html
    ports:
      - 8889:80
    networks:
      - default
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: lesson9-app
    volumes:
      - ./:/var/www/html
    networks:
      - default
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: testproject
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default
volumes:
  mysql-data: