version: '3'
services:
  web:
    image: nginx:1.16.0-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - ${WEB_PORT}:80
    networks:
      - lbpapp

  engine:
    build: ./docker/php
    environment:
      CRYPT_SECRET: ${CRYPT_SECRET}
      NYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./:/var/www/html
    networks:
      - lbpapp

networks:
  lbpapp:
    driver: "bridge"