version: '3'

services:
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - 8889:80

  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: testproject
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: