version: '3'
services:
  web:
    image: nginx:1.16.0-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - ${WEB_PORT}:80
    networks:
      - lbpapp

  engine:
    build: ./docker/php
    environment:
      CRYPT_SECRET: ${CRYPT_SECRET}
      NYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./:/var/www/html
    networks:
      - lbpapp

  db:
    image: mysql:5.7
    container_name: lesson9-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - lbpapp

  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080
    networks:
      - lbpapp

volumes:
  mysql-data:
    driver: "local"

networks:
  lbpapp:
    driver: "bridge"