version: '3'
services:
  web:
    image: nginx:1.16.0-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - ${WEB_PORT}:80
    networks:
      - lbpapp

  engine:
    build: ./docker/php
    volumes:
      - ./:/var/www/html
    networks:
      - lbpapp

networks:
  lbpapp:
    driver: "bridge"